[package]
name = "open2dh"
version = "0.1.0"
authors = ["l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# with every dependency added we get closer and closer to NPM levels of dependency

[dependencies]
parking_lot = "0.11.1"
flume = "0.10.0"
lazy_static = "1.4.0"
thiserror = "1.0.22"
ron = "0.6.2"
serde = "1.0.117"
usb_enumeration = "0.1.0"
regex = "1.4.2"
tch = "0.3.1"
#downcast-rs = "1.2.0"
#scheduled-thread-pool = "0.2.5"
nalgebra = "0.24.0"
image = "0.23.12"
windows = "0.3.1"
suspend = "0.1.3"
#numpy = "0.13.0"
once_cell = "1.6.0"

#[dependencies.pyo3]
#version = "0.13.2"
#features = ["auto-initialize"]

[dependencies.rusty_pool]
version = "0.5.0"
default-features = false

[dependencies.uvc-sys]
version = "0.2.0"
features = ["vendor"]

[dependencies.opencv]
version = "0.49.1"
features = ["clang-runtime"]

[dependencies.uvc]
version = "0.2.0"
features = ["vendor"]

[dependencies.gdnative]
version = "0.9.3"

[dependencies.dlib-face-recognition]
git = "https://github.com/l1npengtul/dlib-face-recognition.git"
version = "0.1.8"
features = ["embed-all", "embed-any"]

[dependencies.cv-convert]
version = "0.3.0"
default-features = false
features = ["opencv-4", "nalgebra"]

[dependencies.v4l]
version = "0.12.0"
features = ["v4l2-sys"]

[dependencies.tensorflow]
version = "0.16.1"
features = ["tensorflow_gpu"]

[build-dependencies]
windows = "0.3.1"


[lib]
crate-type = ["cdylib"]


