[package]
name = "open2dh"
version = "0.1.0"
authors = ["l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# with every dependency added we get closer and closer to NPM levels of dependency

[dependencies]
parking_lot = "0.11.0"
flume = "0.9.1"
lazy_static = "1.4.0"
thiserror = "1.0.22"
cv-core = "0.15.0"
rayon = "1.5.0"
ron = "0.6.2"
serde = "1.0.117"
usb_enumeration = "0.1.0"
rscam = "0.5.5"

[dependencies.uvc] # TODO: Change back to cargo crate when updated
git = "https://github.com/mulimoen/libuvc-rs.git"
features = ["vendor"]

[dependencies.gdnative]
version = "0.9.1"
features = ["bindings"]

[dependencies.dlib-face-recognition]
version = "0.1.7"
features = ["embed-all"]

[dependencies.v4l]
git = "https://github.com/l1npengtul/libv4l-rs" # v4l2-sys-mit is out-of-date on crates.io so were using the git repo until its updated


#[dependencies.opencv]
#version = "0.46.3"
#features = ["buildtime-bindgen", "clang-runtime"]

[lib]
crate-type = ["cdylib"]

