[package]
name = "open2dh"
version = "0.1.0"
authors = ["l1npengtul <l1npengtul@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# with every dependency added we get closer and closer to NPM levels of dependency

[dependencies]
parking_lot = "0.11.1"
flume = "0.10.0"
lazy_static = "1.4.0"
thiserror = "1.0.24"
ron = "0.6.2"
serde = "1.0.117"
usb_enumeration = "0.1.0"
regex = "1.4.2"
image = "0.23.12"
dirs = "3.0.1"

# Safety unknown. Replace when merged
[dependencies.ouroboros]
version = "0.8.3"

[dependencies.rusty_pool]
version = "0.5.1"
default-features = false

[dependencies.opencv]
version = "0.49.1"
features = ["clang-runtime"]

[dependencies.uvc]
version = "0.2.0"
features = ["vendor"]

[dependencies.gdnative]
version = "0.9.3"

[dependencies.dlib-face-recognition]
git = "https://github.com/l1npengtul/dlib-face-recognition.git"
features = ["embed-all", "embed-any"]

[dependencies.v4l]
version = "0.12.0"
features = ["v4l2-sys"]

[dependencies.tvm]
version = "0.1.1-alpha"
default-features = false
features = ["static-linking"]

[dependencies.native-dialog]
version = "0.5.5"
features = ["windows_dpi_awareness", "windows_visual_styles"]

[build-dependencies]
cargo_metadata = "0.13.1"

[lib]
crate-type = ["cdylib"]


